version: '3.3'

services:
  server_one:
    container_name: server_one
    restart: on-failure
    build: .
    ports:
      - '8001:3000'
  server_two:
    container_name: server_two
    restart: on-failure
    build: .
    ports:
      - '8002:3000'
  server_three:
    container_name: server_three
    restart: on-failure
    build: .
    ports:
      - '8003:3000'
  server_four:
    container_name: server_four
    restart: on-failure
    build: .
    ports:
      - '8004:3000'
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'test123'
      POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    # depends_on:
    #   - server

volumes:
  data:
