version: '3.3'

services:
  server:
    build: .
    ports:
      - '3000:3000'
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'test123'
      POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data
  redis:
    image: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes    

volumes:
  data: